/**
 * K3Blocks — 内置静态 emoji 表（200+ 常用，含中英文关键词）。
 * keywords 同时含英文别名与中文，过滤走 fuzzyMatch（子序列模糊匹配）。
 */
import { fuzzyMatch } from "../schema";

export interface K3EmojiItem {
  emoji: string;
  /** 中英文关键词（空格分隔） */
  keywords: string;
}

export const EMOJI_GRID_COLUMNS = 8;

/** 菜单一次最多展示的条数（8 列 × 6 行） */
export const EMOJI_MENU_LIMIT = 48;

/** 模糊过滤 emoji 候选（关键词 + emoji 本体），最多返回 limit 条 */
export function filterEmojiItems(query: string, limit = EMOJI_MENU_LIMIT): K3EmojiItem[] {
  const q = query.trim();
  if (!q) return EMOJI_LIST.slice(0, limit);
  const out: K3EmojiItem[] = [];
  for (const item of EMOJI_LIST) {
    if (fuzzyMatch(q, `${item.keywords} ${item.emoji}`)) {
      out.push(item);
      if (out.length >= limit) break;
    }
  }
  return out;
}

const E = (emoji: string, keywords: string): K3EmojiItem => ({ emoji, keywords });

export const EMOJI_LIST: K3EmojiItem[] = [
  /* 笑脸 / Smileys */
  E("😀", "grinning smile happy 笑 开心 高兴"),
  E("😃", "smiley smile happy 笑 开心"),
  E("😄", "smile grin happy 笑 大笑 开心"),
  E("😁", "grin beaming 笑 咧嘴"),
  E("😆", "laughing xd haha 笑 大笑 哈哈"),
  E("😅", "sweat smile laugh 苦笑 尴尬 汗"),
  E("🤣", "rofl laugh rolling 笑翻 爆笑 哈哈"),
  E("😂", "joy laugh tears 笑哭 爆笑"),
  E("🙂", "slightly smiling 微笑"),
  E("🙃", "upside down 倒脸 调皮"),
  E("😉", "wink 眨眼 调皮"),
  E("😊", "blush smiling 微笑 害羞 开心"),
  E("😇", "innocent angel halo 天使 纯洁"),
  E("🥰", "smiling hearts love 爱 喜欢 心动"),
  E("😍", "heart eyes love 爱心眼 喜欢 爱"),
  E("🤩", "star struck 星星眼 激动"),
  E("😘", "kiss 亲吻 飞吻"),
  E("😗", "kissing 亲吻"),
  E("😋", "yum delicious 好吃 美味 馋"),
  E("😛", "tongue 吐舌 调皮"),
  E("😜", "wink tongue 眨眼吐舌 调皮"),
  E("🤪", "zany crazy 疯狂 搞怪"),
  E("😝", "squinting tongue 吐舌"),
  E("🤑", "money mouth 钱 发财"),
  E("🤗", "hug hugging 拥抱 抱抱"),
  E("🤭", "hand over mouth 捂嘴 偷笑"),
  E("🤫", "shush quiet 嘘 安静"),
  E("🤔", "thinking hmm 思考 想 考虑"),
  E("🫡", "salute 敬礼 收到"),
  E("🤐", "zipper mouth 闭嘴 保密"),
  E("🤨", "raised eyebrow 挑眉 怀疑"),
  E("😐", "neutral 面无表情"),
  E("😑", "expressionless 无语"),
  E("😶", "no mouth 沉默 无语"),
  E("😏", "smirk 得意 坏笑"),
  E("😒", "unamused 不屑 翻白眼"),
  E("🙄", "eye roll 翻白眼 无语"),
  E("😬", "grimacing 龇牙 尴尬"),
  E("🤥", "lying nose 说谎 骗子"),
  E("😌", "relieved 欣慰 松口气"),
  E("😔", "pensive sad 沉思 难过"),
  E("😪", "sleepy 困 想睡"),
  E("🤤", "drooling 流口水 馋"),
  E("😴", "sleeping zzz 睡觉 困"),
  E("😷", "mask sick 口罩 生病"),
  E("🤒", "thermometer sick 发烧 生病"),
  E("🤕", "bandage hurt 受伤"),
  E("🤢", "nauseated 恶心"),
  E("🤮", "vomiting 呕吐 恶心"),
  E("🤧", "sneezing 打喷嚏 感冒"),
  E("🥵", "hot heat 热 炎热"),
  E("🥶", "cold freezing 冷 冰冻"),
  E("🥴", "woozy drunk 晕 醉"),
  E("😵", "dizzy 晕 眼花"),
  E("🤯", "exploding head mind blown 爆炸 震惊"),
  E("🤠", "cowboy 牛仔"),
  E("🥳", "partying celebrate 庆祝 派对"),
  E("😎", "sunglasses cool 酷 墨镜 帅"),
  E("🤓", "nerd glasses 书呆子 学霸"),
  E("🧐", "monocle 观察 研究"),
  E("😕", "confused 困惑"),
  E("😟", "worried 担心"),
  E("🙁", "frown sad 难过 不开心"),
  E("😮", "open mouth surprised 惊讶"),
  E("😯", "hushed 惊讶"),
  E("😲", "astonished shocked 震惊"),
  E("😳", "flushed 脸红 害羞"),
  E("🥺", "pleading puppy eyes 恳求 可怜 拜托"),
  E("😢", "cry sad 哭 伤心"),
  E("😭", "sob cry loudly 大哭 痛哭"),
  E("😱", "scream fear 尖叫 害怕"),
  E("😖", "confounded 痛苦 纠结"),
  E("😞", "disappointed 失望 沮丧"),
  E("😓", "downcast sweat 无奈 汗"),
  E("😩", "weary tired 疲惫 累"),
  E("😤", "triumph steam 生气 哼"),
  E("😡", "rage angry 愤怒 生气"),
  E("😠", "angry mad 生气"),
  E("🤬", "cursing swearing 骂人 爆粗"),
  E("💀", "skull dead 骷髅 笑死"),
  E("💩", "poop 便便 屎"),
  E("🤡", "clown 小丑"),
  E("👻", "ghost 鬼 幽灵"),
  E("👽", "alien 外星人"),
  E("🤖", "robot 机器人"),
  E("🎃", "pumpkin halloween 南瓜 万圣节"),
  E("😺", "cat smile 猫 笑"),
  E("🙈", "see no evil monkey 捂眼 猴子 不敢看"),
  E("🙉", "hear no evil monkey 捂耳 猴子"),
  E("🙊", "speak no evil monkey 捂嘴 猴子"),
  /* 手势 / Gestures */
  E("👍", "thumbs up like good 赞 好 点赞"),
  E("👎", "thumbs down dislike 踩 差"),
  E("👌", "ok hand 好 可以"),
  E("✌️", "victory peace 胜利 耶"),
  E("🤞", "crossed fingers luck 祈祷 好运"),
  E("🤟", "love you 爱你"),
  E("🤘", "rock 摇滚"),
  E("🤙", "call me 打电话"),
  E("👈", "point left 左 指"),
  E("👉", "point right 右 指"),
  E("👆", "point up 上 指"),
  E("👇", "point down 下 指"),
  E("☝️", "index up 注意 指上"),
  E("✋", "raised hand stop 举手 停"),
  E("🤚", "raised back hand 举手"),
  E("🖐️", "open hand 五指 手掌"),
  E("🖖", "vulcan spock 瓦肯 敬礼"),
  E("👋", "wave hello bye 挥手 你好 再见"),
  E("🤝", "handshake deal 握手 合作"),
  E("👏", "clap applause 鼓掌 拍手"),
  E("🙌", "raised hands celebrate 庆祝 万岁"),
  E("👐", "open hands 张开双手"),
  E("🤲", "palms up 捧 祈求"),
  E("🙏", "pray thanks please 拜托 感谢 祈祷"),
  E("✍️", "writing 写 签名"),
  E("💪", "muscle strong flex 加油 强壮 肌肉"),
  E("🫶", "heart hands 比心 爱心"),
  E("👀", "eyes look see 看 眼睛 围观"),
  E("🫵", "point you 指你"),
  /* 心形 / Hearts */
  E("❤️", "red heart love 红心 爱心 爱"),
  E("🧡", "orange heart 橙心 爱"),
  E("💛", "yellow heart 黄心 爱"),
  E("💚", "green heart 绿心 爱"),
  E("💙", "blue heart 蓝心 爱"),
  E("💜", "purple heart 紫心 爱"),
  E("🖤", "black heart 黑心 爱"),
  E("🤍", "white heart 白心 爱"),
  E("🤎", "brown heart 棕心 爱"),
  E("💔", "broken heart 心碎 伤心"),
  E("💕", "two hearts 爱心 爱"),
  E("💖", "sparkling heart 爱心 闪"),
  E("💗", "growing heart 心动 爱"),
  E("💘", "cupid heart 丘比特 爱"),
  E("💝", "heart ribbon 礼物 爱心"),
  E("💯", "hundred perfect 一百 满分 完美"),
  /* 动物自然 / Animals & Nature */
  E("🐶", "dog puppy 狗 小狗"),
  E("🐱", "cat kitten 猫 小猫"),
  E("🐭", "mouse 老鼠"),
  E("🐹", "hamster 仓鼠"),
  E("🐰", "rabbit bunny 兔子"),
  E("🦊", "fox 狐狸"),
  E("🐻", "bear 熊"),
  E("🐼", "panda 熊猫"),
  E("🐨", "koala 考拉"),
  E("🐯", "tiger 老虎"),
  E("🦁", "lion 狮子"),
  E("🐮", "cow 牛"),
  E("🐷", "pig 猪"),
  E("🐸", "frog 青蛙"),
  E("🐵", "monkey 猴子"),
  E("🐔", "chicken 鸡"),
  E("🐧", "penguin 企鹅"),
  E("🐦", "bird 鸟"),
  E("🦆", "duck 鸭子"),
  E("🦅", "eagle 鹰"),
  E("🦉", "owl 猫头鹰"),
  E("🦄", "unicorn 独角兽"),
  E("🐝", "bee 蜜蜂"),
  E("🦋", "butterfly 蝴蝶"),
  E("🐌", "snail 蜗牛"),
  E("🐢", "turtle 乌龟"),
  E("🐍", "snake 蛇"),
  E("🐙", "octopus 章鱼"),
  E("🦑", "squid 鱿鱼"),
  E("🦐", "shrimp 虾"),
  E("🐠", "fish 鱼"),
  E("🐬", "dolphin 海豚"),
  E("🐳", "whale 鲸鱼"),
  E("🦈", "shark 鲨鱼"),
  E("🌸", "cherry blossom flower 樱花 花"),
  E("🌹", "rose flower 玫瑰 花"),
  E("🌻", "sunflower 向日葵"),
  E("🌷", "tulip 郁金香"),
  E("🌱", "seedling sprout 发芽 幼苗"),
  E("🌲", "evergreen tree 松树 树"),
  E("🌴", "palm tree 椰子树"),
  E("🍀", "four leaf clover luck 四叶草 幸运"),
  E("🍁", "maple leaf autumn 枫叶 秋天"),
  E("🌵", "cactus 仙人掌"),
  E("🌊", "wave ocean 海浪 大海"),
  /* 食物 / Food */
  E("🍎", "apple red 苹果"),
  E("🍊", "orange tangerine 橘子 橙子"),
  E("🍋", "lemon 柠檬"),
  E("🍉", "watermelon 西瓜"),
  E("🍇", "grapes 葡萄"),
  E("🍓", "strawberry 草莓"),
  E("🍑", "peach 桃子"),
  E("🍒", "cherries 樱桃"),
  E("🥭", "mango 芒果"),
  E("🍍", "pineapple 菠萝"),
  E("🥝", "kiwi 猕猴桃"),
  E("🍅", "tomato 西红柿"),
  E("🥑", "avocado 牛油果"),
  E("🌶️", "hot pepper spicy 辣椒 辣"),
  E("🍚", "rice 米饭"),
  E("🍜", "noodles ramen 面条 拉面"),
  E("🍝", "spaghetti pasta 意面"),
  E("🍞", "bread 面包"),
  E("🍔", "hamburger burger 汉堡"),
  E("🍟", "fries 薯条"),
  E("🍕", "pizza 披萨"),
  E("🌮", "taco 塔可"),
  E("🍣", "sushi 寿司"),
  E("🍦", "ice cream 冰淇淋"),
  E("🍰", "cake 蛋糕"),
  E("🎂", "birthday cake 生日蛋糕"),
  E("🍩", "donut 甜甜圈"),
  E("🍪", "cookie 饼干"),
  E("🍫", "chocolate 巧克力"),
  E("🍬", "candy 糖果"),
  E("🍿", "popcorn 爆米花"),
  E("☕", "coffee 咖啡"),
  E("🍵", "tea 茶"),
  E("🧋", "boba bubble tea 奶茶 珍珠奶茶"),
  E("🍺", "beer 啤酒"),
  E("🍻", "beers cheers 干杯 啤酒"),
  E("🥂", "champagne cheers 香槟 干杯"),
  E("🍷", "wine 红酒"),
  E("🥤", "cup straw 饮料"),
  /* 活动 / Activities */
  E("⚽", "soccer football 足球"),
  E("🏀", "basketball 篮球"),
  E("🏈", "american football 橄榄球"),
  E("⚾", "baseball 棒球"),
  E("🎾", "tennis 网球"),
  E("🏐", "volleyball 排球"),
  E("🏓", "ping pong 乒乓球"),
  E("🏸", "badminton 羽毛球"),
  E("🎱", "billiards 台球"),
  E("🎮", "video game 游戏 游戏机"),
  E("🎲", "dice 骰子"),
  E("🎯", "dart target 目标 飞镖 命中"),
  E("🎳", "bowling 保龄球"),
  E("🎸", "guitar 吉他"),
  E("🎹", "piano 钢琴"),
  E("🎤", "microphone sing 麦克风 唱歌"),
  E("🎧", "headphones music 耳机 音乐"),
  E("🎬", "clapper movie 电影 拍摄"),
  E("🎨", "art paint 艺术 画画"),
  E("🎪", "circus 马戏团"),
  E("🎫", "ticket 票"),
  E("🏆", "trophy champion 奖杯 冠军"),
  E("🥇", "gold medal first 金牌 第一"),
  E("🥈", "silver medal 银牌 第二"),
  E("🥉", "bronze medal 铜牌 第三"),
  E("🎁", "gift present 礼物"),
  E("🎈", "balloon 气球"),
  E("🎉", "party tada celebrate 庆祝 撒花"),
  E("🎊", "confetti 庆祝 彩带"),
  E("🎄", "christmas tree 圣诞树"),
  E("🧨", "firecracker 鞭炮"),
  E("🎆", "fireworks 烟花"),
  /* 旅行地点 / Travel & Places */
  E("🚗", "car 汽车 车"),
  E("🚕", "taxi 出租车"),
  E("🚌", "bus 公交车"),
  E("🚲", "bike bicycle 自行车"),
  E("🚀", "rocket launch 火箭 发射"),
  E("✈️", "airplane flight 飞机"),
  E("🚄", "bullet train 高铁 动车"),
  E("🚢", "ship 船"),
  E("⛵", "sailboat 帆船"),
  E("🏠", "house home 家 房子"),
  E("🏢", "office building 办公楼"),
  E("🏥", "hospital 医院"),
  E("🏫", "school 学校"),
  E("⛰️", "mountain 山"),
  E("🌋", "volcano 火山"),
  E("🏖️", "beach 海滩"),
  E("🏝️", "island 岛"),
  E("🌇", "sunset city 夕阳 城市"),
  E("🌃", "night city 夜景"),
  E("🗼", "tower tokyo 塔 东京塔"),
  E("🗽", "statue liberty 自由女神"),
  E("⛺", "camping tent 露营 帐篷"),
  /* 天气 / Sky & Weather */
  E("☀️", "sun sunny 太阳 晴"),
  E("🌤️", "sun cloud 多云"),
  E("⛅", "partly cloudy 多云"),
  E("☁️", "cloud 云"),
  E("🌧️", "rain 下雨 雨"),
  E("⛈️", "thunderstorm 雷雨"),
  E("🌩️", "lightning 闪电"),
  E("❄️", "snowflake 雪花 雪"),
  E("⛄", "snowman 雪人"),
  E("🌈", "rainbow 彩虹"),
  E("🌙", "crescent moon 月亮"),
  E("⭐", "star 星星"),
  E("🌟", "glowing star 闪亮 星星"),
  E("✨", "sparkles 闪光 亮晶晶"),
  E("⚡", "zap lightning 闪电 快"),
  E("🔥", "fire hot 火 热 燃"),
  E("💧", "droplet water 水滴"),
  E("🌍", "earth globe 地球"),
  /* 物品 / Objects */
  E("📱", "phone mobile 手机"),
  E("💻", "laptop computer 电脑 笔记本"),
  E("⌚", "watch 手表"),
  E("📷", "camera 相机"),
  E("🔋", "battery 电池"),
  E("💡", "bulb idea 灯泡 主意 想法"),
  E("🔦", "flashlight 手电筒"),
  E("📖", "book open 书 阅读"),
  E("📚", "books 书籍"),
  E("📝", "memo note 笔记 备忘"),
  E("✏️", "pencil 铅笔"),
  E("🖊️", "pen 钢笔"),
  E("📌", "pin 图钉"),
  E("📎", "paperclip 回形针"),
  E("✂️", "scissors 剪刀"),
  E("🔒", "lock 锁 锁定"),
  E("🔑", "key 钥匙"),
  E("🔨", "hammer 锤子"),
  E("🔧", "wrench 扳手 工具"),
  E("⚙️", "gear settings 齿轮 设置"),
  E("🧲", "magnet 磁铁"),
  E("🧪", "test tube 试管 实验"),
  E("🔬", "microscope 显微镜"),
  E("🔭", "telescope 望远镜"),
  E("💊", "pill medicine 药"),
  E("💉", "syringe 注射 疫苗"),
  E("🧸", "teddy bear 玩具熊"),
  E("🛒", "shopping cart 购物车"),
  E("💰", "money bag 钱袋 钱"),
  E("💳", "credit card 信用卡"),
  E("💎", "gem diamond 钻石 宝石"),
  E("📦", "package box 包裹 盒子"),
  E("📮", "mailbox 邮箱"),
  E("✉️", "envelope mail 信封 邮件"),
  E("📅", "calendar 日历 日期"),
  E("📈", "chart up 上涨 增长 图表"),
  E("📉", "chart down 下跌 下降"),
  E("📊", "bar chart 图表 统计"),
  E("⏰", "alarm clock 闹钟"),
  E("⌛", "hourglass 沙漏 时间"),
  E("🕐", "clock one 一点 时间 钟"),
  /* 符号 / Symbols */
  E("✅", "check done 完成 对 勾"),
  E("❌", "cross wrong 错 叉"),
  E("⭕", "circle correct 圈 对"),
  E("❗", "exclamation important 感叹号 重要"),
  E("❓", "question 问号 疑问"),
  E("⚠️", "warning 警告 注意"),
  E("🚫", "prohibited no 禁止"),
  E("♻️", "recycle 回收 循环"),
  E("🔔", "bell notification 铃铛 通知"),
  E("🔕", "bell slash mute 静音"),
  E("🎵", "music note 音乐 音符"),
  E("🏳️‍🌈", "rainbow flag pride 彩虹旗"),
  E("🚩", "red flag 红旗 标记"),
  E("🏁", "checkered flag finish 终点 完成"),
  E("➕", "plus add 加"),
  E("➖", "minus 减"),
  E("💲", "dollar money 美元 钱"),
  E("🆕", "new 新"),
  E("🆒", "cool 酷"),
  E("🆗", "ok 好"),
  E("🔝", "top 顶部 第一"),
  E("♾️", "infinity 无限"),
];
